#!/bin/bash

export CUR_DIR=${PWD}

export EXP_FOLDER=/Volumes/Denali_MRI/kohler/fMRI_EXP/MULTIFOVEA
export SUBJECTS_DIR=/Volumes/svndl/anatomy/FREESURFER_SUBS

cd ${EXP_FOLDER}

for SUBJ in $(ls -d *nl-0027* )
do

	if  [ $SUBJ = "20150506_nl-0033" ];then
		subname="skeri0003"
	else
		subname=${SUBJ#*_}
	fi

	#do surface
	cd ${EXP_FOLDER}/${SUBJ}

	if [ -f ${EXP_FOLDER}/${SUBJ}/refAnat_fp_al+orig.HEAD ]
		then
		refAnat='refAnat_fp_al'
	else
		refAnat='refAnat_al'
	fi
	
	if [ ! -f ${EXP_FOLDER}/${SUBJ}/${subname}_fs4_SurfVol_Alnd_Exp+orig.HEAD ]
		then
		@SUMA_AlignToExperiment -align_centers -overwrite_resp O \
 							-surf_anat ${SUBJECTS_DIR}/${subname}_fs4/SUMA/${subname}_fs4_SurfVol+orig. \
							-exp_anat ${EXP_FOLDER}/${SUBJ}/${refAnat}+orig. -prefix ${EXP_FOLDER}/${SUBJ}/${subname}_fs4_SurfVol_Alnd_Exp+orig. -strip_skull surf_anat
	fi

	# make directory and copy reference epi and anatomy
	if [ ! -d ${EXP_FOLDER}/${SUBJ}/ROIs ]
		then
		mkdir ${EXP_FOLDER}/${SUBJ}/ROIs
	fi

	cd ${EXP_FOLDER}/${SUBJ}/ROIs
	
	if [ -f ${EXP_FOLDER}/${SUBJ}/ROIs/${refAnat}+orig.HEAD ]
		then
		rm ${refAnat}+orig*
	fi
	
	3dcopy ../${refAnat}+orig .
	cp ../ref_epi* .

	#clean up 
	for hemi in rh lh
		do
			# WANG
			cd ${SUBJECTS_DIR}/${subname}_fs4/wang_atlas
			rm ${EXP_FOLDER}/${SUBJ}/ROIs/${hemi}.wang_atlas*
			mriSurf2Vol.py ${subname} ${hemi}.wang_atlas_cluster.niml.dset \
					   --outdir ${EXP_FOLDER}/${SUBJ}/ROIs \
					   --surfvol ${EXP_FOLDER}/${SUBJ}/${subname}_fs4_SurfVol_Alnd_Exp+orig \
					   --mapfunc mode 
			
			# BENSON
			cd ${SUBJECTS_DIR}/${subname}_fs4/benson_atlas
			rm ${EXP_FOLDER}/${SUBJ}/ROIs/${hemi}.eccen.V1-V3model*
			mriSurf2Vol.py ${subname} ${hemi}.all.benson_atlas.niml.dset \
					   --outdir ${EXP_FOLDER}/${SUBJ}/ROIs \
					   --surfvol ${EXP_FOLDER}/${SUBJ}/${subname}_fs4_SurfVol_Alnd_Exp+orig \
					   --mapfunc ave 

			cd ${EXP_FOLDER}/${SUBJ}/ROIs

			3dresample -master ${EXP_FOLDER}/${SUBJ}/ref_epi.ts.do.vr.nii.gz -prefix ${hemi}.wangatlas_rs.nii.gz -inset ${hemi}.wang_atlas_cluster.nii.gz
			3dresample -master ${EXP_FOLDER}/${SUBJ}/ref_epi.ts.do.vr.nii.gz -prefix ${hemi}.eccen.V1-V3model_rs.nii.gz -inset ${hemi}.all.benson_atlas.nii.gz[1]
			
			if [ ${hemi} = lh ]; then
				rm ${subname}_eccen.V1-V3model_al_mask.nii*
	   		    3dcalc -a lh.eccen.V1-V3model_rs.nii.gz -b rh.eccen.V1-V3model_rs.nii.gz \
	   				-expr 'iszero(and(a,b))*(a+b)' -prefix ${subname}_eccen.V1-V3model_al_mask.nii.gz
			fi
	done

done

cd ${CUR_DIR}	
	
	
	 
