#!/bin/bash

export doExp="1"
export testMode="off"

export CUR_DIR=${PWD}
if [ ${doExp} = "2" ]; then
	echo "Running Experiment 2"
	export TOP_DIR=/Volumes/Denali_4D2/kohler/fMRI_EXP/CS_DISP
else
	echo "Running Experiment 1"
	export TOP_DIR=/Volumes/Denali_MRI/kohler/fMRI_EXP/MULTIFOVEA
fi

cd ${TOP_DIR}
SUBFOLDERS=(`ls -d 201*`)

export FS_DIR=/Volumes/svndl/anatomy/FREESURFER_SUBS
export ALT_FS=/Volumes/svndl/anatomy/__OLD_DATA/FREESURFER_SUBS

export SUFFIX='vr.sc.dt'

for FULL_DIR in ${SUBFOLDERS[@]}
do
	[ -d "${FULL_DIR}" ] || continue
	cd ${FULL_DIR}
	SUB=${FULL_DIR##*_}

	echo ${FULL_DIR}

	# TAKE CARE OF IMPROPERLY NAMED SUBJECT
	if [ "${SUB}" = "nl-0033" ]
		then
		export SUB='skeri0003'
	fi

	# USE ALTERNATE DIRECTORY FOR EXP2 SUBS, IF THEY ARE NOT IN STANDARD DIR
	if [ -d ${FS_DIR}/${SUB}_fs4 ]
	then
		export SUBJECTS_DIR=${FS_DIR}
	else
		export SUBJECTS_DIR=${ALT_FS}
	fi

	# MAKE TARGET DIRECTORIES, IF WE THEY DO NOT ALREADY EXIST
	if [ ! -d "${TOP_DIR}/${FULL_DIR}/SURF" ]; then
		mkdir ${TOP_DIR}/${FULL_DIR}/SURF
	fi
	if [ ! -d "${TOP_DIR}/${FULL_DIR}/SURF/run_surf" ]; then
		mkdir ${TOP_DIR}/${FULL_DIR}/SURF/run_surf
	fi	
	if [ ${doExp} = "2" ]; then
		declare -a condNames=("C1vsC2" "C2vsC3" "C1vsC3")
	else
		if [ "${SUB}" = "skeri0004" ] || [ "${SUB}" = "nl-0022" ]; then
			declare -a condNames=("cont" "mofo")
		else
			declare -a condNames=("cont" "mofo" "disp")
		fi
	fi
	# NOW DO IT, FIRST MASK
	export MASKOUT=(`ls -f ${TOP_DIR}/${FULL_DIR}/SURF/run_surf/*${SUB}_mask.niml.dset`)
	# check if output exists
	if [ -z ${MASKOUT} ]
		then
		if [ $testMode = "off" ]; then
			3dcopy ${TOP_DIR}/${FULL_DIR}/ROIs/${SUB}_mask.nii.gz ${SUB}_mask.nii.gz
			mriVol2Surf.py --mapfunc mode --std141 --surfvol ${SUB}_fs4_SurfVol_Alnd_Exp+orig. ${SUB} ${SUB}_mask.nii.gz
			# now move files
			mv *${SUB}_mask.niml.dset ${TOP_DIR}/${FULL_DIR}/SURF/run_surf/.
			rm ${SUB}_mask.nii.gz
		else
			echo "test mode: would run mriVol2Surf.py on ${SUB} mask"
		fi 
	fi

	# ... THEN DATA
	for exp in "${condNames[@]}"
	do
		export OUT=(`ls -f ${TOP_DIR}/${FULL_DIR}/SURF/run_surf/*run*${exp}*.niml.dset`)
		# check if output exists
		if [ -z ${OUT} ]
			then
			if [ $testMode = "off" ]; then
				mriVol2Surf.py --mapfunc ave --std141 --surfvol ${SUB}_fs4_SurfVol_Alnd_Exp+orig. ${SUB} run*${exp}*.nii.gz
				# now move files
				mv *run*niml.dset* ${TOP_DIR}/${FULL_DIR}/SURF/run_surf/.
			else
				echo "test mode: would run mriVol2Surf.py on ${SUB} condition $exp"
			fi 
		fi
		export SMOOTHOUT=(`ls -f ${TOP_DIR}/${FULL_DIR}/SURF/run_surf/*run*${exp}*3fwhm*.niml.dset`)
		# check if output exists
		if [ -z ${SMOOTHOUT} ]
			then	
			if [ $testMode = "off" ]; then
				# SURFSMOOTH REQUIRES THAT YOU ARE IN SAME FOLDER AS FILES
				cd ${TOP_DIR}/${FULL_DIR}/SURF/run_surf
				export SURF_FILES=(`ls -f *run*${exp}*.niml.dset`)
				mriSurfSmooth.py --blursize 3 --std141 ${SUB} ${SURF_FILES[@]}
				cd ${TOP_DIR}/${FULL_DIR}
			else
				echo "test mode: would run mriSurfSmooth.py on ${SUB} condition $exp"
			fi
		fi
	done
	
    cd ${TOP_DIR}
done
# return to current directory
cd ${CUR_DIR}