#!/bin/bash

codeFolder=${PWD}
expFolder=/Volumes/Denali_MRI/kohler/fMRI_EXP/MULTIFOVEA_ATT/



cd ${expFolder}


for sub in 201*
	do
		cd ${sub}/raw_data

		fileList=($(ls | grep -e 'run.*_1.nii.gz' | grep -v 'inplane' | grep -v 'unwarp'))
		refEpi=${fileList[${#fileList[@]}-1]}
		refName=${refEpi%%.nii.gz}
		mriPre.py --ref ${refName}.nii.gz --trdur 2 --pre_tr 6 --tfile ${expFolder}/sliceTiming/mux2_2secs_60total_timing ${fileList[@]}
		mriVolreg.py --ref ${refName}.ts.do.nii.gz run*ts.do.nii.gz
		mriScale.py run*vr.nii.gz
		3dcopy ${refName}.ts.do.vr.nii.gz ../refEpi.ts.do.vr.nii.gz
		mv run*ts.do.vr.sc.dt.nii.gz ../.
	done
	
cd ${codeFolder}