#!/bin/bash

codeFolder=${PWD}
expFolder=/Volumes/Denali_MRI/kohler/fMRI_EXP/MULTIFOVEA_ATT/



cd ${expFolder}


for sub in 20171205_*
	do
		cd ${sub}/raw_data

		fileList=($(ls | grep -e 'run.*.nii.gz' | grep -v 'inplane' | grep -v 'unwarp'))
		refEpi=${fileList[${#fileList[@]}-1]}
		refName=${refEpi%%.nii.gz}
		mriPre.py --ref ${refName}.nii.gz --trdur 2 --pre_tr 6 --tfile ${expFolder}/sliceTiming/mux2_2secs_60total_timing ${fileList[@]}
		mriVolreg.py --ref ${refName}.ts.do.nii.gz run*ts.do.nii.gz
		mriScale.py run*vr.nii.gz
		3dcopy ${refName}.ts.do.vr.nii.gz ../refEpi.ts.do.vr.nii.gz
		mv run*ts.do.vr.sc.dt.nii.gz ../.
	done
	
cd ${codeFolder}

# afterwards, align EPIs to anatomical from the other experiment
# 3dcopy ../../MULTIFOVEA/20160301_nl-0039/nl-0039_fs4_SurfVol_Alnd_Exp+orig. .
# refAnat='nl-0039_fs4_SurfVol_Alnd_Exp'
# align_epi_anat.py -anat ${refAnat}+orig -epi refEpi.ts.do.vr.nii.gz \
#	-epi_base 5 -anat_has_skull no -epi2anat -epi_strip 3dSkullStrip \
#	-rigid_body -volreg off -tshift off -ginormous_move -rigid_body -child_epi run0*
#for run in run*ts.do.vr.sc.dt.nii.gz; do 3dAFNItoNIFTI -prefix ${run%.nii.gz}_al.nii.gz ${run%.nii.gz}_al+orig; rm ${run%.nii.gz}_al+orig*; done 